//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by img_wall.rc
//
#define IDB_BITMAP_WALL                 101
#define IDB_BITMAP_FROG                 102
#define IDB_BITMAP_STONE                103
#define IDB_BITMAP_SNAKE1               104
#define IDB_BITMAP_CLEAR                105
#define IDB_BITMAP_SNAKE2               106
#define IDB_BITMAP_SNAKE3               107
#define IDB_BITMAP_SNAKE4               108
#define IDB_BITMAP_SPEED                109
#define IDB_BITMAP_SLOW                 110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
