/*
 * typedefs.h
 * Game objects types declarations.
 * Bob Rutsky <rutsky_v@rambler.ru>
 * 23.04.2007
 */

#ifndef _TYPEDEFS_H_
#define _TYPEDEFS_H_

typedef struct tagBoardDescr BoardDescr;
typedef struct tagSnake Snake;
typedef struct tagBonus Bonus;
typedef struct tagGameDescr GameDescr;

#include "dir.h"
#include "timer.h"
#include "random.h"
#include "board.h"
#include "snake.h"
#include "bonus.h"
#include "game.h"

#endif /* _TYPEDEFS_H_ */

/* END OF 'typedefs.h' FILE */
